import { k2DFont } from '@/fonts';
import './styles/globals.css';
import { Providers } from './Providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${k2DFont.variable} ${k2DFont.className} `}
        suppressHydrationWarning={true}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
